---
plugin:
  id: "batch-correction"
  name: "Batch Effect Correction"
  description: "Correct for batch effects in proteomics data"
  version: "1.0.0"
  repository: "https://github.com/noatgnu/batch-correction-plugin"
  author: "CauldronGO Team"
  category: "preprocessing"
  icon: "sync_alt"

runtime:
  environments: ["r"]
  entrypoint: "batch_correction.R"

inputs:
  - name: "input_file"
    label: "Input File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Data file with batch effects"

  - name: "annotation_file"
    label: "Annotation File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Sample annotation file with 'Sample' and 'Batch' columns"

  - name: "columns_name"
    label: "Sample Columns"
    type: "column-selector"
    required: true
    multiple: true
    sourceFile: "input_file"
    description: "Select columns containing sample data"

  - name: "method"
    label: "Correction Method"
    type: "select"
    required: true
    default: "combat"
    options:
      - "combat"
      - "limma"
      - "ruvseq"
    description: "Method to use for batch correction"

  - name: "preserve_column"
    label: "Preserve Column"
    type: "text"
    required: false
    description: "Column name from annotation file to preserve during correction (e.g., Condition, BioReplicate)"

  - name: "use_log2"
    label: "Use Log2"
    type: "boolean"
    default: false
    description: "Apply log2 transformation before correction"

outputs:
  - name: "corrected_data"
    path: "batch_corrected.data.txt"
    type: "data"
    description: "Batch-corrected data matrix"
    format: "tsv"

  - name: "batch_info"
    path: "batch_info.txt"
    type: "data"
    description: "Batch correction summary information"
    format: "tsv"

annotation:
  samplesFrom: "columns_name"
  annotationFile: "annotation_file"

execution:
  argsMapping:
    input_file: "--file_path"
    annotation_file: "--batch_info"
    columns_name:
      flag: "--sample_cols"
      transform: "comma-join"
    method: "--method"
    preserve_column: "--preserve_column"
    use_log2:
      flag: "--use_log2"
      when: "true"
      value: "true"

  outputDir: "--output_folder"

  requirements:
    r: ">=4.0"
    packages:
      - "sva"
      - "limma"
      - "RUVSeq"

example:
  enabled: true
  values:
    input_file: "diann/imputed.data.txt"
    annotation_file: "differential_analysis/batch_info.txt"
    columns_name_source: "diann/imputed.data.txt"
    columns_name:
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-IP_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-IP_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-MockIP_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-MockIP_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_Pepide-CBQCA_LT-IP_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_Pepide-CBQCA_LT-IP_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_Pepide-CBQCA_LT-MockIP_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_Pepide-CBQCA_LT-MockIP_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-WCL_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-WCL_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_Pepide-CBQCA_LT-WCL_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_Pepide-CBQCA_LT-WCL_02.raw'
    method: "combat"
    use_log2: false
